"""
Django settings for bazarna project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2=@6ne*bhsuw#t^inbg*7fs5h5*@&h)(1f90mp45jp1oh+f(o@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['bazar-production-f1e0.up.railway.app','127.0.0.1','elbazaare.com']
CSRF_TRUSTED_ORIGINS = [
    'https://bazar-production-f1e0.up.railway.app','http://127.0.0.1:8000/','https://elbazaare.com'
]

# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',    
    'accounts',
    'store',
    'support',
    'merchant_panel',
    'supervisor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'bazarna.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'bazarna.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

import os

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


AUTH_USER_MODEL = 'accounts.User'


SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    # الباك إند الجديد الخاص بنا (الأهم)
    'django.contrib.auth.backends.ModelBackend',
    'accounts.backends.EmailPhoneUsernameBackend', 
    
    # باك إند allauth (ضروري لتسجيل جوجل وغيره)
    'allauth.account.auth_backends.AuthenticationBackend',
]
SOCIALACCOUNT_AUTO_SIGNUP = True # إنشاء الحساب فوراً
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_LOGIN_ON_GET = True
LOGIN_REDIRECT_URL = '/'  # التوجيه بعد الدخول
LOGOUT_REDIRECT_URL = '/accounts/login/' 
ACCOUNT_EMAIL_REQUIRED = False 
ACCOUNT_USERNAME_REQUIRED = False  # <--- مهم جداً: لا تطلب اسم مستخدم
ACCOUNT_AUTHENTICATION_METHOD = 'username_email' # أو 'username_email'
ACCOUNT_EMAIL_VERIFICATION = 'none' # لا ترسل إيميل تفعيل

# إعدادات Google (مؤقتة حتى نحصل على المفاتيح الحقيقية)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '162436305938-dgm742mia7glvb61q0hha93bv94bf9cl.apps.googleusercontent.com',  # مفتاح وهمي للتجربة
            'secret': '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',     # مفتاح وهمي
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'VERIFIED_EMAIL': True
    }
}

SOCIALACCOUNT_FORMS = {
    'signup': 'accounts.forms.MySocialSignupForm',
}
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.MySocialAccountAdapter'
# ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter' # الافتراضي

# Paymob Configuration
PAYMOB_API_KEY = "ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmpiR0Z6Y3lJNklrMWxjbU5vWVc1MElpd2ljSEp2Wm1sc1pWOXdheUk2TVRFeE9EWXdNQ3dpYm1GdFpTSTZJbWx1YVhScFlXd2lmUS5BX0o3bGZPa2wwdmJtU3VpcWZ1aEhNUHNiQ1A4blNEbzI3dFY4Mm5wVUhYTlhLSFZaZUJlNEw2eHpmQXB0SWJEdWstTHlISnNlVlYteXBTNDBwU0pBdw=="
PAYMOB_INTEGRATION_ID_CARD = "5450551"  # Online Card Integration ID
PAYMOB_INTEGRATION_ID_WALLET = "5450696" # Online Wallet Integration ID
PAYMOB_IFRAME_ID = "991968" # Iframe ID

